version: '3.2'
services:
  mysql-roombids:
    image: cloyne/mysql-dev
    container_name: mysql-roombids
    volumes:
      - ./development/db:/var/lib/mysql
      - ./development/log/mysql:/var/log/mysql

  blog:
    build: .
    depends_on:
        - mysql-roombids
    container_name: roombids
    ports:
      - "80:80"
    volumes:
      - ./development/etc/wordpress:/etc/wordpress
      - ./development/etc/service/nginx/run.initialization:/etc/service/nginx/run.initialization
      - ./plugins:/wordpress/wp-content/plugins
      - ./themes:/wordpress/wp-content/themes
      - ./development/log/nginx:/var/log/nginx
